### ISSUE TITLE
Bokeh 0.7.1 release

### ISSUE THREAD

**Issue by bryevdv** [bokeh/Bokeh.jl#13]
@samuelcolvin we are planning to have a 0.7.1 release Monday. This is a point release and will not have a huge announcement (no blog, for instance) but certainly some social media pushes. Would you like bokeh.jl to be featured in any of these materials?

**Comment by samuelcolvin** [comment]
thanks for the offer, I'd prefer to wait until I'm ready to release the updated Bokeh.jl as package and then push or wait until the next release of Bokeh after that.

Make sense?

**Comment by bryevdv** [comment]
Perfect, I was just checking in. FYI the next release Bokeh 0.8 is tentatively scheduled for mid February. We can certainly mention Bokeh.jl then, but just so you know that release is also expected to have the R bindings announcement.

**Comment by samuelcolvin** [comment]
Sounds good, I should have time before then to get Bokeh.jl polished and ready for a proper release.

Be warned though; Julia's bindings will embarrass anything available in less elegant languages. :smile:

**Comment by bryevdv** [comment]
I look forward to it! :D
