### ISSUE TITLE
imbedding components

### ISSUE THREAD

**Issue by meaningofshape** [bokeh/Bokeh.jl#23]
Thank you for working on a Bokeh binding for Julia.  What would this python code look like in Julia? 
```python
from bokeh.plotting import figure
from bokeh.resources import CDN
from bokeh.embed import file_html

plot = figure()
plot.circle([1,2], [3,4])

html = file_html(plot, CDN, "my plot")
```

**Comment by samuelcolvin** [comment]
(small note: having code as code in github is really helpful).

sorry not to reply easlier, I either didn't notice this or noticed on my phone and never got round to remembering it.

I'm guessing the above code using the pydata CDN to loads the js and css files? There's currently no way of doing that with with Bokeh.jl, you can see from [here](https://github.com/bokeh/Bokeh.jl/blob/master/src/generate.jl#L154-L159) we we always use a relative path to the file. However if you wanted this feature it should be pretty easy to implement.

Why do you want to use a CDN? If it's just to avoid reliance on files in relative directories you can use
```julia
using Bokeh
Bokeh.includejs(true)
```
To include the js and css files in the generated html file. This is how the docs work, see [here](https://github.com/bokeh/Bokeh.jl/blob/master/docs/examples/build_all.jl#L3).

**Comment by meaningofshape** [comment]
Thank you for the reply, Samuel.  I don't necessarily need to use CDN, I am just trying to follow some Bokeh examples.  I am a statistician who has never written stand-alone applications.  Julia is fun to write computational models in and Bokeh is very interesting.   


     On Tuesday, August 4, 2015 2:15 PM, Samuel Colvin <notifications@github.com> wrote:
   

 (small note: having code as code in github is really helpful).sorry not to reply easlier, I either didn't notice this or noticed on my phone and never got round to remembering it.I'm guessing the above code using the pydata CDN to loads the js and css files? There's currently no way of doing that with with Bokeh.jl, you can see from here we we always use a relative path to the file. However if you wanted this feature it should be pretty easy to implement.Why do you want to use a CDN? If it's just to avoid reliance on files in relative directories you can useusing Bokeh
Bokeh.includejs(true)To include the js and css files in the generated html file. This is how the docs work, see here.—

**Comment by samuelcolvin** [comment]
Really glad to hear the library is useful. 

Feel free to keep asking questions as and when they occur to you, I'll do my best to reply.
