### ISSUE TITLE
adding meta data to points in plots

### ISSUE THREAD

**Issue by pevnak** [bokeh/Bokeh.jl#35]
Hi,
I have seen in bokeh that you can attach a metadata to plots, such that when you hover over point, there is a window / bubble shown next to it. Is it possible to do the same in Bokeh.jl? It would be great feature for me.

Thanks for an answer.

**Comment by samuelcolvin** [comment]
Hi, @pevnak. It's not possible at the moment.

As you can see from the commit history I've pretty much stopped working on Bokeh.jl so won't be building the feature in the near future. If you would like to implement it I'd be happy to merge a PR.

**Comment by bryevdv** [comment]
@samuelcolvin I'm not too familiar with the Julia community, are there good places we could message or promote to to see if there are any folks interested in picking up the torch?

**Comment by samuelcolvin** [comment]
well @spencerlyon2 had taken over but I believe he's not working on Bokeh.jl right now, am I right?

The google groups mailing list would probably be the best place to ask.

**Comment by spencerlyon2** [comment]
Yes, sorry @samuelcolvin @bryevdv I no longer have substantial open source time to allocate here.

I agree that the julia-users google group is probably the best place to look for a maintainer

**Comment by bryevdv** [comment]
OK I just sent a message there.
